In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [4]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset[['charges']]

In [5]:
indep

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [6]:
dep

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [7]:
from sklearn.ensemble import RandomForestRegressor

In [9]:
from sklearn.model_selection import GridSearchCV
#from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['mse','mae'],
'max_features': ['auto','sqrt','log2'],
'n_estimators':[10,100]}
grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose= 3,n_jobs=-1)
# fitting the model for grid search
grid.fit(indep, dep)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

C:\Users\Rajesh\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:926: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)
C:\Users\Rajesh\Anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:398: FutureWarning: Criterion 'mae' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='absolute_error'` which is equivalent.
  FutureWarning,

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['mse', 'mae'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [10]:
# print best parameter after tuning
# print(grid.best_params_)
re=grid.cv_results_

print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'mae', 'max_features': 'log2', 'n_estimators': 100}:

In [12]:
table=pd.DataFrame.from_dict(re)

In [13]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.082232,0.011203,0.011199,0.006154,mse,auto,10,"{'criterion': 'mse', 'max_features': 'auto', '...",0.850838,0.749991,0.862631,0.809212,0.834235,0.821381,0.039948,7
1,0.471800,0.055931,0.038170,0.013097,mse,auto,100,"{'criterion': 'mse', 'max_features': 'auto', '...",0.843323,0.774704,0.857425,0.818146,0.836996,0.826119,0.028640,5
2,0.058567,0.013454,0.011522,0.003323,mse,sqrt,10,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.839613,0.757663,0.854044,0.808132,0.817822,0.815455,0.033081,10
3,0.479920,0.014115,0.038037,0.004505,mse,sqrt,100,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.855747,0.774501,0.859600,0.832575,0.839123,0.832309,0.030602,3
4,0.065444,0.014592,0.009771,0.003331,mse,log2,10,"{'criterion': 'mse', 'max_features': 'log2', '...",0.847590,0.749968,0.843074,0.806075,0.829549,0.815251,0.035694,11
5,0.419806,0.051732,0.029131,0.011014,mse,log2,100,"{'criterion': 'mse', 'max_features': 'log2', '...",0.858039,0.776431,0.860494,0.826398,0.837281,0.831728,0.030452,4
6,0.347032,0.023598,0.013551,0.006803,mae,auto,10,"{'criterion': 'mae', 'max_features': 'auto', '...",0.837318,0.752221,0.841944,0.793616,0.837975,0.812615,0.034991,12
7,3.139757,0.035702,0.028631,0.003805,mae,auto,100,"{'criterion': 'mae', 'max_features': 'auto', '...",0.840622,0.765856,0.853262,0.826820,0.831038,0.823520,0.030231,6
8,0.180648,0.003918,0.007994,0.000003,mae,sqrt,10,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.839155,0.752653,0.839310,0.818442,0.831125,0.816137,0.032641,9
9,1.885195,0.095569,0.034450,0.013031,mae,sqrt,100,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.856758,0.785292,0.851498,0.830527,0.843719,0.833559,0.025699,2
10,0.179259,0.012427,0.011313,0.006515,mae,log2,10,"{'criterion': 'mae', 'max_features': 'log2', '...",0.844833,0.751111,0.828613,0.811078,0.845796,0.816286,0.034965,8
11,1.878640,0.105331,0.025298,0.007904,mae,log2,100,"{'criterion': 'mae', 'max_features': 'log2', '...",0.864045,0.780518,0.858866,0.825882,0.845599,0.834982,0.030256,1

In [14]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:56
BMI:40
Children:2
Sex Male 0 or 1:0
Smoker Yes 0 or 1:1

In [15]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
#change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[46157.53639545]

C:\Users\Rajesh\Anaconda3\lib\site-packages\sklearn\base.py:442: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  "X does not have valid feature names, but"

In [22]:
import pickle
filename="finalized_model_InsRFGrid.sav"

In [23]:
pickle.dump(grid,open(filename,'wb'))

In [25]:
loaded_model=pickle.load(open("finalized_model_InsRFGrid.sav",'rb'))
result=loaded_model.predict([[61,36,2,0,1]])

C:\Users\Rajesh\Anaconda3\lib\site-packages\sklearn\base.py:442: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  "X does not have valid feature names, but"

In [26]:
result

array([46121.40825515])